<!DOCTYPE html>
<html class="no-js">
<head>
<style type="text/css">
	body { background: #c7ebfb;}
	#list-category-results { width: 80%;margin: 0 auto;}
	#sort-options li {display: inline-block; padding-right: 7px;}
	#sort-options {display: inline-block;}
	i {font-size: 12px; }
</style>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>Kayak Latest Deals - Flights from LAS</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="js/script.js"></script>
</head>
<body>

<!-- Sorting Navigation -->
 <img src="images/sortascend.png" width="50px" /><span style="font-size: 28px">Sort By</span>      
        <ul id="sort-options" class="clearfix">
            <li>
                <a href="#" id="sPrice" class="btnSort">
                    Price
                </a>
            </li>
            <li>
                <a href="#" id="sStyle" class="btnSort">
                    Arrival City
                </a>
            </li>
            <li>
                <a href="#" id="sAirline" class="btnSort">
                    Airline
                </a>
            </li>
            
        </ul>

<h1>Latest Deals</h1>
 
<ul id="list-category-results" class="clearfix">
         

<?php 
        foreach ($models as $model) {
				$title = $model->title;
				$price = substr($title, 12, 3);
				$arrive = substr($title, 7, 3);
				$depart = substr($title, 0, 3);
				$departDate = substr($title, 15, 7);
				preg_match('/on (.*?) found/',$title, $display);
				
				echo "<li><h3>" . $title . "</h3>";
                echo "<div class='flights'>";
				echo "<h2>" . $model->originCode . "</h2>";
				echo "Price: <span class='price'>$" . $price . "</span></br>";
				echo "Departure Airport: " . $depart . "</br>";
				echo "Arrival Airport: <span class='alpha'>" . $arrive . "</span></br></br>";
				echo "Airline: <span class='airline'>" . $display[1] . "</span></br></br>";
				echo "Departure Date: <span class='depart'>" . $departDate . "</span></br></br>";
				 echo "<a href=" . $model->link . ">Click here for more info</a></br></br>";
                echo "<i>Published on: " . $model->pubDate . "</i></div></li>";
               
        }
?>

</ul>

</body>
</html>